### PR TITLE
Exclude item whether it's a file or a directory

### PR DESCRIPTION
**Pull request by vvrein**

### CODE REVIEW

**Comment by xy2z** [comment]
Thanks @vvrein 
Looks good, i willl have to test it out later.
But the documentation (README) also needs to be changed. I think it's easiest to keep the config name "exclude_files" for upgrading purposes, but I think the text "List of files to exclude. Supports regex if the format is /regex/i." should be updated to include dirs. And I believe the text is also in the default config file.

**Comment by vvrein** [comment]
Ok, I see, thanks, will try to fix this!

**Comment by vvrein** [comment]
I doubt about `or || and` terminology in this case.
or - can be understood like `just files OR just directories`
and - :thinking: 
Any thoughts?

**Comment by xy2z** [comment]
'Or' is fine, i think most people can understand that.

**Comment by vvrein** [comment]
Oops, sorry, this commit isn't intended to go here

**Comment by xy2z** [comment]
Works great 👍 thanks!

**Pull request merged**
